import { VektisCode } from './code';

//https://www.vektis.nl/standaardisatie/codelijsten/COD032-NEN
export const VektisCountry = [
	new VektisCode('AD', 'ANDORRA'),
	new VektisCode('AE', 'VERENIGDE ARABISCHE EMIRATEN'),
	new VektisCode('AF', 'AFGHANISTAN'),
	new VektisCode('AG', 'ANTIGUA EN BARBUDA'),
	new VektisCode('AI', 'ANGUILA'),
	new VektisCode('AL', 'ALBANIË'),
	new VektisCode('AM', 'ARMENIË'),
	new VektisCode('AN', 'NEDERLANDSE ANTILLEN'),
	new VektisCode('AO', 'ANGOLA'),
	new VektisCode('AQ', 'ANTARTICA'),
	new VektisCode('AR', 'ARGENTINIË'),
	new VektisCode('AS', 'AMERIKAANS-SAMOA'),
	new VektisCode('AT', 'OOSTENRIJK'),
	new VektisCode('AU', 'AUSTRALIË'),
	new VektisCode('AW', 'ARUBA'),
	new VektisCode('AX', 'ÅLANDSEILANDEN'),
	new VektisCode('AZ', 'AZERBEIDZJAN'),
	new VektisCode('BA', 'BOSNIË EN HERZEGOVINA'),
	new VektisCode('BB', 'BARBADOS'),
	new VektisCode('BD', 'BANGLADESH'),
	new VektisCode('BE', 'BELGIË'),
	new VektisCode('BF', 'BURKINA FASO'),
	new VektisCode('BG', 'BULGARIJE'),
	new VektisCode('BH', 'BAHREIN'),
	new VektisCode('BI', 'BURUNDI'),
	new VektisCode('BJ', 'BENIN'),
	new VektisCode('BL', 'SAINT BARTHÉLEMY'),
	new VektisCode('BM', 'BERMUDA'),
	new VektisCode('BN', 'BRUNEI'),
	new VektisCode('BO', 'BOLIVIA'),
	new VektisCode('BQ', 'BONAIRE, SINT EUSTATIUS en SABA'),
	new VektisCode('BR', 'BRAZILIË'),
	new VektisCode('BS', "BAHAMA'S"),
	new VektisCode('BT', 'BHUTAN'),
	new VektisCode('BV', 'BOUVET'),
	new VektisCode('BW', 'BOTSWANA'),
	new VektisCode('BY', 'WIT-RUSLAND'),
	new VektisCode('BZ', 'BELIZE'),
	new VektisCode('CA', 'CANADA'),
	new VektisCode('CC', 'COCOSEILANDEN'),
	new VektisCode('CD', 'CONGO-KINSHASA'),
	new VektisCode('CF', 'CENTRAAL-AFRIKAANSE REPUBLIEK'),
	new VektisCode('CG', 'CONGO-BRAZZAVILLE'),
	new VektisCode('CH', 'ZWITSERLAND'),
	new VektisCode('CI', 'IVOORKUST'),
	new VektisCode('CK', 'COOKEILANDEN'),
	new VektisCode('CL', 'CHILI'),
	new VektisCode('CM', 'KAMEROEN'),
	new VektisCode('CN', 'CHINA'),
	new VektisCode('CO', 'COLOMBIA'),
	new VektisCode('CR', 'COSTA RICA'),
	new VektisCode('CU', 'CUBA'),
	new VektisCode('CV', 'KAAPVERDIË'),
	new VektisCode('CW', 'CURAÇAO'),
	new VektisCode('CX', 'CHRISTMASEILAND'),
	new VektisCode('CY', 'CYPRUS'),
	new VektisCode('CZ', 'TSJECHIË'),
	new VektisCode('DE', 'DUITSLAND'),
	new VektisCode('DJ', 'DJIBOUTI'),
	new VektisCode('DK', 'DENEMARKEN'),
	new VektisCode('DM', 'DOMINICA'),
	new VektisCode('DO', 'DOMINICAANSE REPUBLIEK'),
	new VektisCode('DZ', 'ALGERIJE'),
	new VektisCode('EC', 'ECUADOR'),
	new VektisCode('EE', 'ESTLAND'),
	new VektisCode('EG', 'EGYPTE'),
	new VektisCode('EH', 'WESTELIJKE SAHARA'),
	new VektisCode('ER', 'ERITREA'),
	new VektisCode('ES', 'SPANJE'),
	new VektisCode('ET', 'ETHIOPIË'),
	new VektisCode('FI', 'FINLAND'),
	new VektisCode('FJ', 'FIJI'),
	new VektisCode('FK', 'FALKLANDEILANDEN'),
	new VektisCode('FM', 'MICRONESIA'),
	new VektisCode('FO', 'FAERÖER'),
	new VektisCode('FR', 'FRANKRIJK'),
	new VektisCode('GA', 'GABON'),
	new VektisCode('GB', 'VERENIGD KONINKRIJK'),
	new VektisCode('GD', 'GRENADA'),
	new VektisCode('GE', 'GEORGIË'),
	new VektisCode('GF', 'FRANS-GUYANA'),
	new VektisCode('GG', 'GUERNSEY'),
	new VektisCode('GH', 'GHANA'),
	new VektisCode('GI', 'GIBRALTAR'),
	new VektisCode('GL', 'GROENLAND'),
	new VektisCode('GM', 'GAMBIA'),
	new VektisCode('GN', 'GUINEA'),
	new VektisCode('GP', 'GUADELOUPE'),
	new VektisCode('GQ', 'EQUATORIAAL-GUINEA'),
	new VektisCode('GR', 'GRIEKENLAND'),
	new VektisCode('GS', 'ZUID-GEORGIË EN DE ZUIDELIJKE SANDWICHEILANDEN'),
	new VektisCode('GT', 'GUATEMALA'),
	new VektisCode('GU', 'GUAM'),
	new VektisCode('GW', 'GUINEE-BISSAU'),
	new VektisCode('GY', 'GUYANA'),
	new VektisCode('HK', 'HONGKONG'),
	new VektisCode('HM', 'HEARD EN MCDONALDEILANDEN'),
	new VektisCode('HN', 'HONDURAS'),
	new VektisCode('HR', 'KROATIË'),
	new VektisCode('HT', 'HAÏTI'),
	new VektisCode('HU', 'HONGARIJE'),
	new VektisCode('ID', 'INDONESIË'),
	new VektisCode('IE', 'IERLAND'),
	new VektisCode('IL', 'ISRAËL'),
	new VektisCode('IM', 'ISLE OF MAN'),
	new VektisCode('IN', 'INDIA'),
	new VektisCode('IO', 'BRITS TERRITORIUM IN DE INDISCHE OCEAAN'),
	new VektisCode('IQ', 'IRAK'),
	new VektisCode('IR', 'IRAN'),
	new VektisCode('IS', 'IJSLAND'),
	new VektisCode('IT', 'ITALIË'),
	new VektisCode('JE', 'JERSEY'),
	new VektisCode('JM', 'JAMAICA'),
	new VektisCode('JO', 'JORDANIË'),
	new VektisCode('JP', 'JAPAN'),
	new VektisCode('KE', 'KENIA'),
	new VektisCode('KG', 'KIRGIZIË'),
	new VektisCode('KH', 'CAMBODJA'),
	new VektisCode('KI', 'KIRIBATI'),
	new VektisCode('KM', 'COMOREN'),
	new VektisCode('KN', 'SAINT KITTS EN NEVIS'),
	new VektisCode('KP', 'NOORD-KOREA'),
	new VektisCode('KR', 'ZUID-KOREA'),
	new VektisCode('KW', 'KOEWEIT'),
	new VektisCode('KY', 'CAYMANEILANDEN'),
	new VektisCode('KZ', 'KAZACHSTAN'),
	new VektisCode('LA', 'LAOS'),
	new VektisCode('LB', 'LIBANON'),
	new VektisCode('LC', 'SAINT LUCIA'),
	new VektisCode('LI', 'LIECHTENSTEIN'),
	new VektisCode('LK', 'SRI LANKA'),
	new VektisCode('LR', 'LIBERIA'),
	new VektisCode('LS', 'LESOTHO'),
	new VektisCode('LT', 'LITOUWEN'),
	new VektisCode('LU', 'LUXEMBURG'),
	new VektisCode('LV', 'LETLAND'),
	new VektisCode('LY', 'LIBIË'),
	new VektisCode('MA', 'MAROKKO'),
	new VektisCode('MC', 'MONACO'),
	new VektisCode('MD', 'MOLDAVIË'),
	new VektisCode('ME', 'MONTENEGRO'),
	new VektisCode('MF', 'SAINT MARTIN'),
	new VektisCode('MG', 'MADAGASKAR'),
	new VektisCode('MH', 'MARSHALLEILANDEN'),
	new VektisCode('MK', 'MACEDONIË'),
	new VektisCode('ML', 'MALI'),
	new VektisCode('MM', 'MYANMAR'),
	new VektisCode('MN', 'MONGOLIË'),
	new VektisCode('MO', 'MACAU'),
	new VektisCode('MP', 'NOORDELIJKE MARIANEN'),
	new VektisCode('MQ', 'MARTINIQUE'),
	new VektisCode('MR', 'MAURITANIË'),
	new VektisCode('MS', 'MONTSERRAT'),
	new VektisCode('MT', 'MALTA'),
	new VektisCode('MU', 'MAURITIUS'),
	new VektisCode('MV', 'MALDIVEN'),
	new VektisCode('MW', 'MALAWI'),
	new VektisCode('MX', 'MEXICO'),
	new VektisCode('MY', 'MALEISIË'),
	new VektisCode('MZ', 'MOZAMBIQUE'),
	new VektisCode('NA', 'NAMIBIË'),
	new VektisCode('NC', 'NIEUW-CALEDONIË'),
	new VektisCode('NE', 'NIGER'),
	new VektisCode('NF', 'NORFOLK'),
	new VektisCode('NG', 'NIGERIA'),
	new VektisCode('NI', 'NICARAGUA'),
	new VektisCode('NL', 'NEDERLAND'),
	new VektisCode('NO', 'NOORWEGEN'),
	new VektisCode('NP', 'NEPAL'),
	new VektisCode('NR', 'NAURU'),
	new VektisCode('NU', 'NIUE'),
	new VektisCode('NZ', 'NIEUW-ZEELAND'),
	new VektisCode('OM', 'OMAN'),
	new VektisCode('PA', 'PANAMA'),
	new VektisCode('PE', 'PERU'),
	new VektisCode('PF', 'FRANS-POLYNESIË'),
	new VektisCode('PG', 'PAPOEA-NIEUW-GUINEA'),
	new VektisCode('PH', 'FILIPIJNEN'),
	new VektisCode('PK', 'PAKISTAN'),
	new VektisCode('PL', 'POLEN'),
	new VektisCode('PM', 'SAINT-PIERRE EN MIQUELON'),
	new VektisCode('PN', 'PITCAIRNEILANDEN'),
	new VektisCode('PR', 'PUERTO RICO'),
	new VektisCode('PS', 'PALESTIJNSE AUTORITEIT'),
	new VektisCode('PT', 'PORTUGAL'),
	new VektisCode('PW', 'PALAU'),
	new VektisCode('PY', 'PARAGUAY'),
	new VektisCode('QA', 'QATAR'),
	new VektisCode('RE', 'RÉUNION'),
	new VektisCode('RO', 'ROEMENIË'),
	new VektisCode('RS', 'SERVIË'),
	new VektisCode('RU', 'RUSLAND'),
	new VektisCode('RW', 'RWANDA'),
	new VektisCode('SA', 'SAOEDI-ARABIË'),
	new VektisCode('SB', 'SALOMONSEILANDEN'),
	new VektisCode('SC', 'SEYCHELLEN'),
	new VektisCode('SD', 'SOEDAN'),
	new VektisCode('SE', 'ZWEDEN'),
	new VektisCode('SG', 'SINGAPORE'),
	new VektisCode('SH', 'SINT-HELENA'),
	new VektisCode('SI', 'SLOVENIË'),
	new VektisCode('SJ', 'SPITSBERGEN EN JAN MAYEN'),
	new VektisCode('SK', 'SLOWAKIJE'),
	new VektisCode('SL', 'SIERRA LEONE'),
	new VektisCode('SM', 'SAN MARINO'),
	new VektisCode('SN', 'SENEGAL'),
	new VektisCode('SO', 'SOMALIË'),
	new VektisCode('SR', 'SURINAME'),
	new VektisCode('SS', 'ZUID SOEDAN'),
	new VektisCode('ST', 'SAO TOMÉ EN PRINCIPE'),
	new VektisCode('SV', 'EL SALVADOR'),
	new VektisCode('SX', 'SINT MAARTEN (Nederlands deel)'),
	new VektisCode('SY', 'SYRIË'),
	new VektisCode('SZ', 'SWAZILAND'),
	new VektisCode('TC', 'TURKS- EN CAICOSEILANDEN'),
	new VektisCode('TD', 'TSJAAD'),
	new VektisCode('TF', 'FRANSE ZUIDELIJKE EN ANTARCTISCHE GEBIEDEN'),
	new VektisCode('TG', 'TOGO'),
	new VektisCode('TH', 'THAILAND'),
	new VektisCode('TJ', 'TADZJIKISTAN'),
	new VektisCode('TK', 'TOKELAU'),
	new VektisCode('TL', 'OOST-TIMOR'),
	new VektisCode('TM', 'TURKMENISTAN'),
	new VektisCode('TN', 'TUNESIË'),
	new VektisCode('TO', 'TONGA'),
	new VektisCode('TR', 'TURKIJE'),
	new VektisCode('TT', 'TRINIDAD EN TOBAGO'),
	new VektisCode('TV', 'TUVALU'),
	new VektisCode('TW', 'TAIWAN'),
	new VektisCode('TZ', 'TANZANIA'),
	new VektisCode('UA', 'OEKRAÏNE'),
	new VektisCode('UG', 'OEGANDA'),
	new VektisCode('UM', 'KLEINE PACIFISCHE EILANDEN VAN DE VERENIGDE STATEN'),
	new VektisCode('US', 'VERENIGDE STATEN'),
	new VektisCode('UY', 'URUGUAY'),
	new VektisCode('UZ', 'OEZBEKISTAN'),
	new VektisCode('VA', 'VATICAANSTAD'),
	new VektisCode('VC', 'SAINT VINCENT EN DE GRENADINES'),
	new VektisCode('VE', 'VENEZUELA'),
	new VektisCode('VG', 'BRITSE MAAGDENEILANDEN'),
	new VektisCode('VI', 'AMERIKAANSE MAAGDENEILANDEN'),
	new VektisCode('VN', 'VIETNAM'),
	new VektisCode('VU', 'VANUATU'),
	new VektisCode('WF', 'WALLIS EN FUTUNA'),
	new VektisCode('WS', 'SAMOA'),
	new VektisCode('XK', 'KOSOVO'),
	new VektisCode('YE', 'JEMEN'),
	new VektisCode('YT', 'MAYOTTE'),
	new VektisCode('ZA', 'ZUID-AFRIKA'),
	new VektisCode('ZM', 'ZAMBIA'),
	new VektisCode('ZW', 'ZIMBABWE')
];
