import { VektisCode } from './code';

// https://www.vektis.nl/standaardisatie/codelijsten/COD459-CIZ
export const VektisGovernmentInstitutes = [
	new VektisCode('0100', 'CIZ Groningen'),
	new VektisCode('0110', 'CIZ locatie Sellingen'),
	new VektisCode('0120', 'CIZ locatie Nieuwe Pekela'),
	new VektisCode('0130', 'CIZ locatie Bedum'),
	new VektisCode('0140', 'CIZ locatie Groningen'),
	new VektisCode('0141', 'CIZ locatie Hoogezand'),
	new VektisCode('0142', 'CIZ locatie Leek'),
	new VektisCode('0200', 'CIZ Regiobureau Leeuwarden'),
	new VektisCode('0210', 'CIZ locatie Leeuwarden'),
	new VektisCode('0220', 'CIZ Locatie Sneek'),
	new VektisCode('0230', 'CIZ locatie Drachten'),
	new VektisCode('0300', 'CIZ Drenthe'),
	new VektisCode('0310', 'CIZ locatie Norg'),
	new VektisCode('0320', 'CIZ locatie Emmen'),
	new VektisCode('0330', 'CIZ locatie Dwingelo'),
	new VektisCode('0400', 'CIZ Zwolle'),
	new VektisCode('0410', 'CIZ locatie Zwolle'),
	new VektisCode('0420', 'CIZ locatie Harderwijk'),
	new VektisCode('0500', 'CIZ Twente'),
	new VektisCode('0510', 'CIZ locatie Almelo'),
	new VektisCode('0520', 'CIZ locatie Hengelo'),
	new VektisCode('0530', 'CIZ locatie Enschede'),
	new VektisCode('0600', 'CIZ Deventer Apeldoorn'),
	new VektisCode('0610', 'Regionaal indicatieorgaan Zutphen e.o.'),
	new VektisCode('0620', 'Stichting Het Scharfshuis'),
	new VektisCode('0630', 'CIZ locatie Apeldoorn'),
	new VektisCode('0700', 'CIZ Gelderland'),
	new VektisCode('0710', 'CIZ locatie Doetinchem'),
	new VektisCode('0720', 'CIZ locatie Groenlo'),
	new VektisCode('0730', 'CIZ locatie Arnhem'),
	new VektisCode('0740', 'St. indicatieorgaan Renkum'),
	new VektisCode('0750', 'CIZ locatie Rheden'),
	new VektisCode('0760', 'CIZ locatie Duiven'),
	new VektisCode('0770', 'CIZ locatie Huissen'),
	new VektisCode('0780', 'RIO Gelderse Vallei'),
	new VektisCode('0790', 'CIZ locatie Ede'),
	new VektisCode('0800', 'CIZ Nijmegen Tiel'),
	new VektisCode('0810', 'CIZ locatie Nijmegen'),
	new VektisCode('0820', 'CIZ locatie Tiel'),
	new VektisCode('0900', 'CIZ Utrecht'),
	new VektisCode('0910', 'CIZ locatie Amersfoort'),
	new VektisCode('0920', 'RIO De Bilt Zeist'),
	new VektisCode('0930', 'RIO Zuidoost Utrecht oost'),
	new VektisCode('0940', 'RIO Zuidoost Utrecht'),
	new VektisCode('0950', 'CIZ locatie Utrecht'),
	new VektisCode('0960', 'Stichting RIO ZWU'),
	new VektisCode('0970', 'RIO West Utrecht'),
	new VektisCode('0980', 'CIZ locatie Heuvelrug'),
	new VektisCode('0981', 'CIZ locatie Zeist'),
	new VektisCode('0982', 'CIZ locatie Maarn'),
	new VektisCode('0983', 'CIZ locatie Veenendaal'),
	new VektisCode('0990', 'CIZ locatie IJsselstein'),
	new VektisCode('1000', 'CIZ Flevoland Almere'),
	new VektisCode('1010', 'CIZ locatie Lelystad'),
	new VektisCode('1020', 'CIZ locatie Almere'),
	new VektisCode('1100', 'CIZ locatie Hilversum'),
	new VektisCode('1200', 'CIZ locatie Noord-Holland Noord'),
	new VektisCode('1210', 'CIZ locatie Hoorn'),
	new VektisCode('1220', 'CIZ locatie Alkmaar'),
	new VektisCode('1230', 'CIZ locatie Den Helder'),
	new VektisCode('1240', 'CIZ locatie Den Helder (Texel Wieringen)'),
	new VektisCode('1300', 'CIZ Haarlem Beverwijk'),
	new VektisCode('1310', 'CIZ locatie Beverwijk'),
	new VektisCode('1320', 'CIZ locatie Haarlem'),
	new VektisCode('1400', 'CIZ Purmerend Zaandam'),
	new VektisCode('1410', 'CIZ locatie Purmerend'),
	new VektisCode('1420', 'CIZ locatie Zaandam'),
	new VektisCode('1500', 'CIZ locatie Amsterdam'),
	new VektisCode('1600', 'CIZ locatie Amstelveen'),
	new VektisCode('1700', 'CIZ Zuid-Holland Zuid'),
	new VektisCode('1710', 'CIZ locatie Noordwijk'),
	new VektisCode('1720', 'CIZ locatie Alphen aan den Rijn'),
	new VektisCode('1730', 'CIZ locatie Leiderdorp'),
	new VektisCode('1800', 'CIZ regio Den Haag'),
	new VektisCode('1810', 'CIZ locatie Voorburg'),
	new VektisCode('1820', 'CIZ locatie Den Haag'),
	new VektisCode('1830', 'CIZ locatie Zoetermeer'),
	new VektisCode('1840', 'CIZ locatie Holland West'),
	new VektisCode('1900', 'CIZ Delft'),
	new VektisCode('1910', 'CIZ locatie Delft'),
	new VektisCode('1920', 'CIZ locatie Bergschenhoek'),
	new VektisCode('2000', 'CIZ locatie Gouda'),
	new VektisCode('2100', 'CIZ regio Rotterdam'),
	new VektisCode('2110', 'CIZ locatie Rotterdam'),
	new VektisCode('2120', 'CIZ locatie Capelle aan den IJssel'),
	new VektisCode('2200', 'CIZ locatie Schiedam'),
	new VektisCode('2300', 'CIZ locatie Ridderkerk'),
	new VektisCode('2310', 'RIOBAR'),
	new VektisCode('2320', 'RIO Voorne, Putten en Rozenburg'),
	new VektisCode('2330', 'RIO Hoekse Waard'),
	new VektisCode('2340', 'RIO Goeree-Overflakkee'),
	new VektisCode('2400', 'CIZ Gorinchem Dordrecht'),
	new VektisCode('2410', 'CIZ locatie Gorinchem'),
	new VektisCode('2420', 'CIZ locatie Dordrecht'),
	new VektisCode('2500', 'CIZ Zeeland'),
	new VektisCode('2510', 'CIZ locatie Goes'),
	new VektisCode('2520', 'CIZ locatie Vlissingen'),
	new VektisCode('2530', 'CIZ locatie Terneuzen'),
	new VektisCode('2540', 'CIZ locatie Sint Maartensdijk'),
	new VektisCode('2600', 'CIZ Noord-Brabant West'),
	new VektisCode('2610', 'CIZ locatie Wouw'),
	new VektisCode('2620', 'CIZ locatie Breda'),
	new VektisCode('2630', 'CIZ locatie Almkerk'),
	new VektisCode('2700', 'CIZ locatie Tilburg'),
	new VektisCode('2800', 'CIZ Noord-Brabant Noord'),
	new VektisCode('2810', 'CIZ locatie Den Bosch'),
	new VektisCode('2820', 'CIZ locatie Oss'),
	new VektisCode('2900', 'CIZ locatie Veldhoven'),
	new VektisCode('2910', 'RIO Eindhoven'),
	new VektisCode('2920', 'RIO Groot Kemperland'),
	new VektisCode('2930', 'RIO Helmond e.o.'),
	new VektisCode('3000', 'CIZ Limburg Midden Noord'),
	new VektisCode('3010', 'CIZ locatie Horst'),
	new VektisCode('3020', 'CIZ locatie Roermond'),
	new VektisCode('3100', 'CIZ Limburg Zuid'),
	new VektisCode('3110', 'CIZ locatie Geleen'),
	new VektisCode('3120', 'CIZ locatie Heerlen'),
	new VektisCode('3130', 'LIO Landgraaf'),
	new VektisCode('3140', 'CIZ locatie Maastricht'),
	new VektisCode('3200', 'CIZ locatie Deventer')
];
