import { VektisCode } from './code';

//https://www.vektis.nl/standaardisatie/codelijsten/COD016-VEKT
export const VektisNurseSpecialism = [
	new VektisCode('0100', 'Huisartsen, niet nader gespecificeerd'),
	new VektisCode('0101', 'Huisarts, Niet apotheekhoudend'),
	new VektisCode('0102', 'Huisarts, medicatiebeoordeling chronisch UR-geneesmiddelgebruik'),
	new VektisCode('0110', 'Huisarts, Apotheekhoudend'),
	new VektisCode('0111', 'Huisartsen, niet apotheekhoudend, medicatiebeoordeling'),
	new VektisCode('0112', 'Huisartsen, Apotheekhoudend, medicatiebeoordeling'),
	new VektisCode('0120', 'Alternatieve huisartsen'),
	new VektisCode('0200', 'Apothekers'),
	new VektisCode('0201', 'Apotheker, medicatiebeoordeling chronisch UR-geneesmiddelgebruik'),
	new VektisCode('0300', 'Medisch specialisten, niet nader gespecificeerd'),
	new VektisCode('0301', 'Medisch specialisten, oogheelkunde'),
	new VektisCode('0302', 'Medisch specialisten, keel-, neus- en oorheelkunde'),
	new VektisCode('0303', 'Chirurgie (Heelkunde)'),
	new VektisCode('0304', 'Medisch specialisten, plastische chirurgie'),
	new VektisCode('0305', 'Medisch specialisten, orthopedie'),
	new VektisCode('0306', 'Medisch specialisten, urologie'),
	new VektisCode('0307', 'Medisch specialisten, obstetrie en gynaecologie'),
	new VektisCode('0308', 'Medisch specialisten, neurochirurgie'),
	new VektisCode('0309', 'Medisch specialisten, zenuw - en zielsziekten'),
	new VektisCode('0310', 'Dermatologie en Venerologie'),
	new VektisCode('0313', 'Interne geneeskunde'),
	new VektisCode('0316', 'Medisch specialisten, kindergeneeskunde'),
	new VektisCode('0318', 'Medisch specialisten, gastro-enterologie (maag-darm-lever-arts)'),
	new VektisCode('0320', 'Medisch specialisten, cardiologie'),
	new VektisCode('0322', 'Medisch specialisten, longziekten'),
	new VektisCode('0324', 'Medisch specialisten, reumatologie'),
	new VektisCode('0326', 'Medisch specialisten, allergologie'),
	new VektisCode('0327', 'Medisch specialisten, revalidatie'),
	new VektisCode('0328', 'Medisch specialisten, cardio thoracale chirurgie'),
	new VektisCode('0329', 'Medisch specialisten, psychiatrie'),
	new VektisCode('0330', 'Medisch specialisten, neurologie'),
	new VektisCode('0335', 'Medisch specialisten, geriatrie'),
	new VektisCode('0360', 'Medisch specialisten, radiologie'),
	new VektisCode('0361', 'Medisch specialisten, radiotherapie'),
	new VektisCode('0362', 'Radiologie'),
	new VektisCode('0363', 'Medisch specialisten, nucleaire geneeskunde'),
	new VektisCode('0386', 'Medisch specialisten, klinische chemie'),
	new VektisCode('0387', 'Medisch specialisten, medische microbiologie'),
	new VektisCode('0388', 'Medisch specialisten, pathologische anatomie'),
	new VektisCode('0389', 'Anesthesiologie'),
	new VektisCode('0390', 'Medisch specialisten, klinische genetica'),
	new VektisCode('0400', 'Fysiotherapeuten, niet nader gespecificeerd'),
	new VektisCode('0401', 'Fysiotherapeuten, fysiotherapie'),
	new VektisCode('0402', 'Fysiotherapeuten, heilgymnastiek/massage'),
	new VektisCode('0403', 'Fysiotherapeuten, kinderfysiotherapie'),
	new VektisCode('0404', 'Fysiotherapeuten, manuele therapie'),
	new VektisCode('0405', 'Fysiotherapeuten, oedeemtherapie'),
	new VektisCode('0406', 'Fysiotherapeuten, bekkenfysiotherapie'),
	new VektisCode('0407', 'Fysiotherapeuten, fysiotherapie in de geriatrie'),
	new VektisCode('0408', 'Fysiotherapeuten, sportfysiotherapie'),
	new VektisCode('0409', 'Fysiotherapeuten, psychosomatische fysiotherapie'),
	new VektisCode('0410', 'Oro-faciale fysiotherapie'),
	new VektisCode('0411', 'Arbeids- en/of bedrijfsfysiotherapeut'),
	new VektisCode('0412', 'Fysiotherapeuten, Oncologie'),
	new VektisCode('0413', 'Fysiotherapeuten, manuele therapie en heilgymnastiek'),
	new VektisCode('0414', 'Fysiotherapeuten, manuele therapie en sportfysiotherapie'),
	new VektisCode('0415', 'Fysiotherapeuten, manuele therapie en kinderfysiotherapie'),
	new VektisCode('0416', 'Fysiotherapeuten, manuele therapie en oedeemtherapie'),
	new VektisCode('0417', 'Fysiotherapeuten, bekkenfysiotherapie en manuele therapie'),
	new VektisCode('0418', 'Fysiotherapeuten, kinderfysio- en oedeemtherapie'),
	new VektisCode('0419', 'Fysiotherapeuten, kinder- en bekkenfysiotherapie'),
	new VektisCode('0420', 'Fysiotherapeuten, bekkenfysio- en oedeemtherapie'),
	new VektisCode('0421', 'Fysiotherapeuten, fysiotherapie in de geriatrie en oedeemtherapie'),
	new VektisCode('0422', 'Fysiotherapeuten, sportfysio- en oedeemtherapie'),
	new VektisCode('0423', 'Fysiotherapeuten, manuele therapie, kinderfysio- en oedeemtherapie'),
	new VektisCode('0424', 'Fysiotherapeuten, manuele therapie, bekkenfysio- en oedeemtherapie'),
	new VektisCode(
		'0425',
		'Fysiotherapeuten, kinderfysio-, bekkenfysiotherapie, en manuele therapie'
	),
	new VektisCode('0426', 'Fysiotherapeuten, kinderfysio-, bekkenfysio- en oedeemtherapie'),
	new VektisCode(
		'0427',
		'Fysiotherapeuten, manuele therapie, kinderfysio-, bekkenfysio- en oedeemtherapie'
	),
	new VektisCode(
		'0428',
		'Fysiotherapeuten, manuele therapie, kinderfysio-, sportfysio-, oedeemtherapie'
	),
	new VektisCode(
		'0429',
		'Fysiotherapeuten, manuele therapie, bekkenfysio-,  sportfysio-, oedeemtherapie, fysiotherapie in de geriatrie'
	),
	new VektisCode(
		'0430',
		'Fysiotherapeuten, manuele therapie, bekkenfysio-, sportfysio- en oedeemtherapie'
	),
	new VektisCode(
		'0431',
		'Fysiotherapeuten, heilgymnastiek/massage en fysiotherapie in de geriatrie'
	),
	new VektisCode('0432', 'Fysiotherapeuten, heilgymnastiek/massage en sportfysiotherapie'),
	new VektisCode(
		'0433',
		'Fysiotherapeuten, manuele therapie, oedeemtherapie, kinder-, bekken- en sportfysiotherapie'
	),
	new VektisCode(
		'0434',
		'Fysiotherapeuten, heilgymnastiek, kinder-, bekken- en sportfysiotherapie, fysiotherapie in de geriatrie'
	),
	new VektisCode('0435', 'Fysiotherapeuten, manuele therapie, kinder- en sportfysiotherapie'),
	new VektisCode(
		'0436',
		'Fysiotherapeuten, manuele therapie, oedeemtherapie en fysiotherapie in de geriatrie'
	),
	new VektisCode(
		'0437',
		'Fysiotherapeuten, manuele therapie, oedeemtherapie, kinder-, bekken- en sportfysiotherapie, fysiotherapie in de geriatrie'
	),
	new VektisCode('0438', 'Fysiotherapeuten, manuele therapie en fysiotherapie in de geriatrie'),
	new VektisCode('0439', 'Fysiotherapeuten, manuele therapie, bekken- en sportfysiotherapie'),
	new VektisCode('0440', 'Fysiotherapeuten, kinderfysiotherapie en fysiotherapie in de geriatrie'),
	new VektisCode('0441', 'Fysiotherapeuten, psychosomatische fysio- en oedeemtherapie'),
	new VektisCode('0442', 'Fysiotherapeuten, psychosomatische fysiotherapie en manuele therapie'),
	new VektisCode('0443', 'Fysiotherapeuten, Psychosomatische fysio- en bekkentherapie'),
	new VektisCode('0444', 'Fysiotherapeuten, Sportfysio-, kinderfysio-, en oedeemtherapie'),
	new VektisCode(
		'0445',
		'Fysiotherapeuten, bekkenfysiotherapie, oedeemtherapie en fysiotherapie in de geriatrie'
	),
	new VektisCode('0446', 'Fysiotherapeuten, kinderfysiotherapie en psychosomatische fysiotherapie'),
	new VektisCode('0447', 'Fysiotherapeuten, sport- en kinderfysiotherapie'),
	new VektisCode('0448', 'Fysiotherapeuten, fysiotherapie en manuele therapie'),
	new VektisCode(
		'0449',
		'Fysiotherapeuten, kinder- en sportfysiotherapie, oedeemtherapie en psychosomatische fysiotherapie'
	),
	new VektisCode('0450', 'Fysiotherapeuten, fysio- en kinderfysiotherapie'),
	new VektisCode('0451', 'Fysiotherapeuten, psychosomatische-, oedeem-, bekkenfysiotherapie'),
	new VektisCode('0452', 'Fysiotherapeuten, psychosomatische- en sportfysiotherapie'),
	new VektisCode('0453', 'Fysiotherapeuten, heilgymnastiek/massage, oedeemtherapie'),
	new VektisCode('0454', 'Fysiotherapeuten, heilgymnastiek, massage en bekkenfysiotherapie'),
	new VektisCode('0455', 'Fysiotherapeuten, psychosomatische, sportfysio- en manuele therapie'),
	new VektisCode(
		'0456',
		'Fysiotherapeuten, heilgymnastiek, massage, geriatrie en psychosomatische fysiotherapie'
	),
	new VektisCode(
		'0457',
		'Fysiotherapeuten, manuele therapie, oedeemtherapie, kinder-, bekkenfysiotherapie en geriatrie'
	),
	new VektisCode(
		'0458',
		'Fysiotherapeuten, manuele therapie, kinderfysiotherapie, oedeemtherapie en geriatrie'
	),
	new VektisCode('0459', 'Fysiotherapeuten, manuele therapie, bekkenfysiotherapie en geriatrie'),
	new VektisCode(
		'0460',
		'Fysiotherapeuten, fysiotherapie, manuele therapie, sportfysiotherapie en geriatrie'
	),
	new VektisCode('0461', 'Fysiotherapeuten, fysiotherapie en heilgymnastiek/massage'),
	new VektisCode('0462', 'Fysiotherapeuten, fysio- en oedeemtherapie (lympfedrainage)'),
	new VektisCode('0463', 'Fysiotherapeuten, fysio- en bekkenfysiotherapie'),
	new VektisCode('0464', 'Fysiotherapeuten, fysio- en fysiotherapie in de geriatrie'),
	new VektisCode('0465', 'Fysiotherapeuten, fysio- en sportfysiotherapie'),
	new VektisCode('0466', 'Fysiotherapeuten, fysio- en psychosomatische fysiotherapie'),
	new VektisCode('0467', 'Fysiotherapeuten, fysio-, manuele- en kinderfysiotherapie'),
	new VektisCode('0468', 'Fysiotherapeuten, fysio-, manuele- en oedeemtherapie'),
	new VektisCode('0469', 'Fysiotherapeuten, fysio-, manuele- en bekkenfysiotherapie'),
	new VektisCode('0470', 'Fysiotherapeuten, fysio-, kinderfysio- en oedeemtherapie'),
	new VektisCode('0471', 'Fysiotherapeuten, fysio-, kinderfysio- en bekkenfysiotherapie'),
	new VektisCode('0472', 'Fysiotherapeuten, fysio-, oedeem- en bekkentherapie'),
	new VektisCode('0473', 'Fysiotherapeuten, fysio-, oedeem- en geriatrische fysiotherapie'),
	new VektisCode('0474', 'Fysiotherapeuten, fysio- en ora-faciaal therapie'),
	new VektisCode('0475', 'Fysiotherapeuten, fysio-, manueel en ora-faciaal therapie'),
	new VektisCode('0476', 'Fysiotherapeuten, fysio-, manueel en arbeidsfysiotherapie'),
	new VektisCode('0477', 'Fysiotherapeut Leefstijlcoach'),
	new VektisCode('0478', 'Hart, vaat en long fysiotherapeut'),
	new VektisCode('0479', 'Hart fysiotherapeut'),
	new VektisCode('0480', 'Vaat fysiotherapeut'),
	new VektisCode('0481', 'Long fysiotherapeut'),
	new VektisCode('0500', 'Logopedisten, niet nader gespecificeerd'),
	new VektisCode('0501', 'Logopedisten, logopedie'),
	new VektisCode('0502', 'Logopedisten, foniatrie'),
	new VektisCode('0503', 'Logopedisten, stottertherapie'),
	new VektisCode('0504', 'Logopedisten, preverbale therapie'),
	new VektisCode('0505', 'Logopedie, direct toegankelijk / 1e lijn'),
	new VektisCode('0506', 'Logopedisten, afasie'),
	new VektisCode('0507', 'Logopedisten, Hanen-ouderprogramma'),
	new VektisCode('0508', 'Logopedisten, Integraal Zorg Stotteren (IZS)'),
	new VektisCode('0510', 'Logopedisten, logopedie, direct toegankelijk'),
	new VektisCode('0511', 'Logopedisten, foniatrie, direct toegankelijk'),
	new VektisCode('0512', 'Logopedisten, stottertherapie, direct toegankelijk'),
	new VektisCode('0513', 'Logopedisten, preverbale therapie, direct toegankelijk'),
	new VektisCode('0514', 'Logopedisten, afasie, direct toegankelijk'),
	new VektisCode('0515', 'Logopedisten, Hanen-ouderenprogramma, direct toegankelijk'),
	new VektisCode('0516', 'Logopedisten, Integraal Stotteren IZS, direct toegankelijk'),
	new VektisCode('0517', 'Preverbale therapie, Hanen-ouderen programma'),
	new VektisCode('0518', 'Stottertherapie, preverbale therapie'),
	new VektisCode('0519', 'Stottertherapie,Integraal Zorg Stotteren (IZS)'),
	new VektisCode('0520', 'Stottertherapie, Hanen-ouderprogramma'),
	new VektisCode('0521', 'Preverbale therapie, Afasie'),
	new VektisCode('0522', 'Afasie, Hanen-ouderprogramma'),
	new VektisCode('0523', 'Stottertherapie, Afasie'),
	new VektisCode('0524', 'Stottertherapie, Afasie, Preverbale therapie'),
	new VektisCode('0525', 'Stottertherapie ,Hanen-ouderprogramma, Afasie, Preverbale therapie'),
	new VektisCode('0526', 'Stottertherapie, Hanen-ouderprogramma,Preverbale therapie'),
	new VektisCode('0527', 'Hanen-ouderprogramma, Preverbale therapie, Direct toegankelijk'),
	new VektisCode('0528', 'Stottertherapie, Preverbale therapie, Direct toegankelijk'),
	new VektisCode('0529', 'Stottertherapie, Preverbale therapie, Afasie, Direct toegankelijk'),
	new VektisCode(
		'0530',
		'Stottertherapie, Preverbale therapie, Afasie, Hanen-ouderprogramma, Direct toegankelijk'
	),
	new VektisCode(
		'0531',
		'Stottertherapie, Preverbale therapie, Hanen-ouderprogramma, Direct toegankelijk'
	),
	new VektisCode('0532', 'Stottertherapie, Integraal Zorg Stotteren (IZS), Direct toegankelijk'),
	new VektisCode('0533', 'Stottertherapie, Hanen-ouderprogramma, Direct toegankelijk'),
	new VektisCode('0534', 'Preverbale therapie, Afasie, Direct toegankelijk'),
	new VektisCode('0535', 'Afasie, Hanen-ouderprogramma, Direct toegankelijk'),
	new VektisCode('0536', 'Stottertherapie, Afasie, Direct toegankelijk'),
	new VektisCode('0600', 'Ziekenhuizen, niet nader gespecificeerd'),
	new VektisCode('0601', 'Ziekenhuizen, algemene ziekenhuizen'),
	new VektisCode('0602', 'Ziekenhuizen, academische ziekenhuizen'),
	new VektisCode('0603', 'Ziekenhuizen, astmaklinieken'),
	new VektisCode('0604', 'Ziekenhuizen, beademingscentra'),
	new VektisCode('0606', 'Ziekenhuizen, epilepsiecentra'),
	new VektisCode('0607', 'Ziekenhuizen, kinderziekenhuizen'),
	new VektisCode('0608', 'Ziekenhuizen, kankerklinieken'),
	new VektisCode('0610', 'Ziekenhuizen, kraamklinieken'),
	new VektisCode('0612', 'Ziekenhuizen, neurologische klinieken'),
	new VektisCode('0613', 'Ziekenhuizen, oogziekenhuizen'),
	new VektisCode('0614', 'Ziekenhuizen, orthopaedische klinieken'),
	new VektisCode('0615', 'Ziekenhuizen, reumaklinieken'),
	new VektisCode('0616', 'Ziekenhuizen, revalidatie-centra'),
	new VektisCode('0617', 'Ziekenhuizen, sanatoria met longklinieken'),
	new VektisCode('0621', 'Ziekenhuizen, sanatoria'),
	new VektisCode('0628', 'Ziekenhuizen, multi-categorale ziekenhuizen'),
	new VektisCode('0629', 'Ziekenhuizen, psychiatrische ziekenhuizen'),
	new VektisCode('0630', 'Ziekenhuizen, militaire ziekenhuizen'),
	new VektisCode('0650', 'Ziekenhuizen, buitenlandse ziekenhuizen'),
	new VektisCode('0700', 'Oefentherapeuten, niet nader gespecificeerd'),
	new VektisCode('0701', 'Oefentherapeuten, methode Cesar'),
	new VektisCode('0702', 'Oefentherapeuten, methode Mensendieck'),
	new VektisCode('0703', 'Oefentherapeuten, kinderoefentherapie'),
	new VektisCode('0704', 'Oefentherapeuten, psychosomatische oefentherapie'),
	new VektisCode('0705', 'Oefentherapeuten, methode cesar, kinderoefentherapie'),
	new VektisCode('0706', 'Oefentherapeuten, methode mensendieck, kinderoefentherapie'),
	new VektisCode('0707', 'Oefentherapeuten, methode cesar, psychosomatische oefentherapie'),
	new VektisCode('0708', 'Oefentherapeuten, methode mensendieck, psychosomatische oefentherapie'),
	new VektisCode('0709', 'Oefentherapeuten, direct toegankelijk'),
	new VektisCode('0710', 'Oefentherapeuten, Methode Cesar, direct toegankelijk'),
	new VektisCode('0711', 'Oefentherapeuten, Methode Mensendieck, direct toegankelijk'),
	new VektisCode('0712', 'Oefentherapeuten, kinderoefentherapie, direct toegankelijk'),
	new VektisCode('0713', 'Oefentherapeuten, psychosomatische oefentherapie, direct toegankelijk'),
	new VektisCode(
		'0714',
		'Oefentherapeuten, Methode Cesar, kinderoefentherapie, direct toegankelijk'
	),
	new VektisCode(
		'0715',
		'Oefentherapeuten, Methode Mensendieck, kinderoefentherapie, direct toegankelijk'
	),
	new VektisCode(
		'0716',
		'Oefentherapeuten, Methode Cesar, psychosomatische oefentherapie, direct toegankelijk'
	),
	new VektisCode(
		'0717',
		'Oefentherapeuten, Methode Mensendieck, psychosomatische oefentherapie, direct toegankelijk'
	),
	new VektisCode('0718', 'Oefentherapeut Leefstijlcoach'),
	new VektisCode('0719', 'Bekkenoefentherapie'),
	new VektisCode('0720', 'Geriatrie Oefentherapie'),
	new VektisCode('0800', 'Verloskundigen, niet nader gespecificeerd'),
	new VektisCode('0801', 'Verloskundigen, met bevoegdheid echoscopie'),
	new VektisCode('0802', 'Verloskundigen, echoscopie NT'),
	new VektisCode('0803', 'Verloskundigen, echoscopie SEO'),
	new VektisCode('0804', 'Verloskundigen, echoscopie uitwendig'),
	new VektisCode('0805', 'Eerste trimester SEO'),
	new VektisCode('0806', 'Tweede trimester SEO'),
	new VektisCode('0807', 'Biometrie echo'),
	new VektisCode('0808', 'Termijn echo'),
	new VektisCode('0809', 'Counseling prenatale screening'),
	new VektisCode('0810', 'Anticonceptie'),
	new VektisCode('0811', 'Antenataal CTG'),
	new VektisCode('1100', 'Tandartsspecialisten mondziekten en kaakchirurgie'),
	new VektisCode('1101', 'Mondzorg en kaakchirurgie, implantoloog'),
	new VektisCode('1200', 'Tandartsen'),
	new VektisCode('1201', 'Tandarts, implantoloog'),
	new VektisCode('1202', 'Tandarts, Pedodontoloog'),
	new VektisCode('1203', 'Tandarts, Endodontoloog'),
	new VektisCode('1210', 'Tandarts algemeen practicus, Pedodontoloog'),
	new VektisCode('1211', 'Tandarts algemeen practicus, Endodontoloog'),
	new VektisCode('1212', 'Tandarts, Endodontoloog, Pedodontoloog'),
	new VektisCode('1213', 'Tandarts algemeen practicus, Pedodontoloog, Endodontoloog'),
	new VektisCode('1300', 'Tandartsspecialisten dentomaxillaire orthopaedie'),
	new VektisCode('1301', 'Tandartsspecialisten dentomaxillaire orthopaedie, Implantologie'),
	new VektisCode('1400', 'Arts arbeid en gezondheid'),
	new VektisCode('1401', 'Arts arbeid en gezondheid, zorgverlener'),
	new VektisCode('1402', 'Arts bedrijfsgeneeskunde'),
	new VektisCode('1403', 'Arts verzekeringsgeneeskunde'),
	new VektisCode('1410', 'Arts arbeid en gezondheid, bedrijfs- en verzekeringsgeneeskunde'),
	new VektisCode('1700', 'Rechtspersonen'),
	new VektisCode('1800', 'Dialysecentra'),
	new VektisCode('1900', 'Audiologische centra'),
	new VektisCode('2000', 'Radiotherapeutische centra'),
	new VektisCode('2100', 'Dienstenstructuren (ANW-diensten)'),
	new VektisCode('2200', 'Zelfstandige behandelcentra (ZBC)'),
	new VektisCode('2270', 'Zelfstandige behandelcentra (EMS)'),
	new VektisCode('2300', 'Inrichtingen voor revalidatiedagbehandeling'),
	new VektisCode('2400', 'Dietisten'),
	new VektisCode('2401', 'Dietisten, direct toegankelijk / 1e lijn'),
	new VektisCode('2402', 'Diëtist Leefstijlcoach'),
	new VektisCode('2410', 'Dietisten, dietist, direct toegankelijk'),
	new VektisCode('2500', 'Inrichtingen voor psychiatrische deeltijdbehandeling'),
	new VektisCode('2600', 'Podotherapeuten'),
	new VektisCode('2601', 'Sportpodotherapeut'),
	new VektisCode('2602', 'Podotherapeuten, sportpodotherapeut'),
	new VektisCode('3000', 'Instelling voor verstandelijk gehandicapten'),
	new VektisCode('3100', 'Bloedbanken'),
	new VektisCode('3200', "GGD's (instellingen)"),
	new VektisCode('3300', 'Kraamcentra'),
	new VektisCode('3301', 'Kraamverzorgenden'),
	new VektisCode('3400', 'Trombosediensten'),
	new VektisCode('3500', 'Instellingen voor visueel gehandicapten'),
	new VektisCode('3600', 'Ambulancevervoerders'),
	new VektisCode('3700', 'Gezondheidscentra'),
	new VektisCode('3800', 'Instellingen voor bijzondere tandheelkunde en mondzorg'),
	new VektisCode('3801', 'Instelling voor bijzondere tandheelkunde, collectief tijdstarief'),
	new VektisCode('3802', 'Instelling voor bijzondere tandheelkunde, individueel tijdstarief'),
	new VektisCode('3803', 'Instelling voor Mondzorg'),
	new VektisCode('3900', 'Regionale instellingen voor jeugdtandverzorging'),
	new VektisCode('4000', 'Instellingen voor auditief gehandicapten'),
	new VektisCode('4100', 'Beheerstichtingen verpleeghuizen, verzorgingshuizen en thuiszorg'),
	new VektisCode('4101', 'ZZP-ers in wijkverpleging'),
	new VektisCode('4102', 'PGB aanbieders'),
	new VektisCode('4200', 'Verzorgingstehuizen'),
	new VektisCode('4300', 'Beheerstichtingen verzorgingshuizen'),
	new VektisCode('4400', 'Optometristen'),
	new VektisCode('4401', 'Optometristen, direct toegankelijk'),
	new VektisCode('4402', 'Orthoptisten'),
	new VektisCode('4500', 'Verpleeginrichtingen somatische zieken'),
	new VektisCode('4600', 'Verpleeginrichtingen psycho-geriatrische patienten'),
	new VektisCode('4700', 'Gecombineerde verpleeginrichtingen'),
	new VektisCode('4800', 'Overige instellingen'),
	new VektisCode('4801', 'Gemeenten'),
	new VektisCode('4802', 'Instelling voor Reizigersvaccinatie'),
	new VektisCode('4803', 'Herstellingsoord'),
	new VektisCode('4804', 'Hospice/Bijna-Thuis-Huis (High-Care)'),
	new VektisCode('4805', 'Zorghotel'),
	new VektisCode('4806', 'Verpleegunit'),
	new VektisCode('4807', 'Mantelzorg makelaar'),
	new VektisCode('4808', 'Preventieve Zorg EHBO-cursus'),
	new VektisCode('4809', 'Preventieve Zorg EHBKO'),
	new VektisCode('4810', 'Preventieve Zorg Reanimatiecursus'),
	new VektisCode('4811', 'Preventieve Zorg AED'),
	new VektisCode('4812', 'Preventieve Zorg Slaaptherapie'),
	new VektisCode('4813', 'Preventieve Zorg Lymfoedeem'),
	new VektisCode('4814', 'Preventieve Zorg Reuma'),
	new VektisCode('4815', 'Preventieve Zorg Hartproblemen'),
	new VektisCode('4816', 'Preventieve Zorg Diabetes type 2'),
	new VektisCode('4817', "Preventieve Zorg Beweegprogramma's"),
	new VektisCode('4818', 'Preventieve Zorg Afvallen'),
	new VektisCode('4819', 'Preventieve Zorg Vrij van alcohol'),
	new VektisCode('4820', 'Preventieve Zorg Stoppen met roken'),
	new VektisCode('4821', 'Preventieve Zorg Healthcheck'),
	new VektisCode('4900', 'Abortusklinieken, beheerstichtingen verpleeghuizen'),
	new VektisCode('5000', 'Laboratoria'),
	new VektisCode('5100', 'Klinisch-genetisch centra'),
	new VektisCode('5200', 'Eurotransplant'),
	new VektisCode('5300', 'Diverse samenwerkingsverbanden, niet nader gespecificeerd.'),
	new VektisCode('5301', 'Ketenzorg DM type 2'),
	new VektisCode('5302', 'Ketenzorg CVR'),
	new VektisCode('5303', 'Ketenzorg COPD'),
	new VektisCode('5304', 'Ketenzorg Reuma'),
	new VektisCode('5305', 'Ketenzorg Astma'),
	new VektisCode('5306', 'O&I Wijksamenwerking'),
	new VektisCode('5307', 'Onderwijs Begeleidingsdiensten (OBD)'),
	new VektisCode('5308', 'Huisarts verplaatste zorg'),
	new VektisCode('5309', 'Dyslexie'),
	new VektisCode('5310', 'Diverse samenwerkingsverbanden, DM type 2 en CVR'),
	new VektisCode('5311', 'Diverse samenwerkingsverbanden, DM type 2, CVR en COPD'),
	new VektisCode('5312', 'Diverse samenwerkingsverbanden, DM type 2 en COPD'),
	new VektisCode('5313', 'Diverse samenwerkingsverbanden, CVR en COPD'),
	new VektisCode('5314', 'Integrale geboortezorg'),
	new VektisCode('5316', 'Samenwerkingsverband GLI'),
	new VektisCode('5321', 'Innovatie experiment voor Huisartsenzorg'),
	new VektisCode('5322', 'Innovatie experiment voor Fysiotherapie'),
	new VektisCode('5323', 'Innovatie experiment voor Kraamzorg'),
	new VektisCode('5324', 'Innovatie experiment voor GGZ'),
	new VektisCode('5400', 'GGZ Instellingen (PUK/PAAZ)'),
	new VektisCode('5600', 'Consultatiebureaus voor alcohol en drugs'),
	new VektisCode('5700', 'Physician Assistant'),
	new VektisCode('5800', "Centrale posten ambulancediensten (CPA's)"),
	new VektisCode('6000', 'Instellingen voor dagverpleging voor ouderen'),
	new VektisCode('6100', 'Beheerstichtingen dagverblijven'),
	new VektisCode('6500', 'Gezinsvervangende tehuizen'),
	new VektisCode('6600', 'Koepels en beheerstichtingen WLZ'),
	new VektisCode('6701', 'Regionetwerk Casemanagement Dementie'),
	new VektisCode('7000', 'Kinderdagverblijven'),
	new VektisCode('7100', 'Betekenisloze vestiging'),
	new VektisCode('7200', 'Regionale instellingen beschermd wonen (RIBW)'),
	new VektisCode('7300', 'WLZ-gecombineerd'),
	new VektisCode('7400', 'ARBO-diensten'),
	new VektisCode('7500', 'Thuiszorg, kruiswerk en gezinsverzorging'),
	new VektisCode('7600', 'Leveranciers hulpmiddelen, niet nader gespecificeerd'),
	new VektisCode('7601', 'Leveranciers hulpmiddelen, ledemaatprothesen'),
	new VektisCode('7602', 'Leveranciers hulpmiddelen, mammaprothesen'),
	new VektisCode('7603', 'Leveranciers hulpmiddelen, oogprothesen'),
	new VektisCode(
		'7604',
		'Leveranciers hulpmiddelen, prothetische voorzieningen voor onder- en bovenkaak'
	),
	new VektisCode('7605', 'Leveranciers hulpmiddelen, gelaatsprothesen'),
	new VektisCode('7606', 'Leveranciers hulpmiddelen, corsetten'),
	new VektisCode('7607', 'Leveranciers hulpmiddelen, orthopedisch schoeisel'),
	new VektisCode('7608', 'Leveranciers hulpmiddelen, overige orthesen'),
	new VektisCode('7609', 'Leveranciers hulpmiddelen, verbandschoenen'),
	new VektisCode('7611', 'Leveranciers hulpmiddelen, brillenglazen'),
	new VektisCode('7612', 'Leveranciers hulpmiddelen, contactlenzen'),
	new VektisCode('7613', 'Leveranciers hulpmiddelen, bijzondere gezichtshulpmiddelen'),
	new VektisCode('7614', 'Leveranciers hulpmiddelen, bijzondere gezichtshulpmiddelen algemeen'),
	new VektisCode('7615', 'Leveranciers hulpmiddelen, bijzondere gezichtshulpmiddelen maatwerk'),
	new VektisCode('7616', 'Leveranciers hulpmiddelen, hoortoestellen'),
	new VektisCode(
		'7617',
		'Leveranciers hulpmiddelen, extern hoortoestel in combinatie met implantaat (BAHA)'
	),
	new VektisCode(
		'7618',
		'Leveranciers hulpmiddelen, maskeerder ter behandeling van oorsuizen (Tinnetusmaskeerder)'
	),
	new VektisCode('7619', 'Leveranciers hulpmiddelen, gehoorhulpmiddelen (inclusief maskeerder)'),
	new VektisCode('7620', 'Leveranciers hulpmiddelen, solo apparatuur'),
	new VektisCode('7621', 'Leveranciers hulpmiddelen, incontinentie-absorptiemateriaal'),
	new VektisCode('7622', 'Leveranciers hulpmiddelen, overige verzorgingsmiddelen'),
	new VektisCode('7623', 'Leveranciers hulpmiddelen, draagbare uitwendige infuuspomp'),
	new VektisCode('7624', 'Leveranciers hulpmiddelen, incontinentie afvoerend materiaal'),
	new VektisCode('7625', 'Leveranciers hulpmiddelen, stoma materialen'),
	new VektisCode('7626', 'Leveranciers hulpmiddelen, slijmuitzuigapparatuur'),
	new VektisCode('7627', 'Leveranciers hulpmiddelen, confectie orthesen'),
	new VektisCode('7628', 'Leveranciers hulpmiddelen, maatwerk orthesen'),
	new VektisCode('7629', 'Leveranciers hulpmiddelen, tracheacanule en stemprothesen'),
	new VektisCode('7630', 'Leveranciers hulpmiddelen, steunzolen'),
	new VektisCode('7631', 'Leveranciers hulpmiddelen, loophulpmiddelen'),
	new VektisCode(
		'7632',
		'Leveranciers hulpmiddelen, eenvoudige hulpmiddelen voor mobiliteit van personen'
	),
	new VektisCode(
		'7633',
		'Leveranciers hulpmiddelen, overige hulpmiddelen voor mobiliteit van personen'
	),
	new VektisCode('7634', 'Leveranciers hulpmiddelen, blindegeleidehonden'),
	new VektisCode('7635', 'Leveranciers hulpmiddelen, hulphonden'),
	new VektisCode('7636', 'Leveranciers hulpmiddelen, pruiken'),
	new VektisCode(
		'7637',
		'Leveranciers hulpmiddelen, arm-, hand-, vingerfunctievervullers (robotarm)'
	),
	new VektisCode('7638', 'Leveranciers hulpmiddelen, anaalspoelapparatuur'),
	new VektisCode('7639', 'Leveranciers hulpmiddelen, plaswekker'),
	new VektisCode('7640', 'Leveranciers hulpmiddelen, bewakingsmonitor voor baby'),
	new VektisCode('7641', 'Leveranciers hulpmiddelen, elastische kousen'),
	new VektisCode('7642', 'Leveranciers hulpmiddelen, allergeenvrije hoezen'),
	new VektisCode('7643', 'Leveranciers hulpmiddelen, verbandmiddelen'),
	new VektisCode('7644', 'Leveranciers hulpmiddelen, UV-B lichttherapie'),
	new VektisCode('7645', 'Leveranciers hulpmiddelen, allergeenvrije schoenen'),
	new VektisCode('7646', 'Leveranciers hulpmiddelen, anti-conceptionele hulpmiddelen'),
	new VektisCode('7647', 'Leveranciers hulpmiddelen, kappen ter bescherming van de schedel'),
	new VektisCode('7649', 'Leveranciers hulpmiddelen, thuisdialyse apparatuur'),
	new VektisCode('7650', 'Leveranciers hulpmiddelen, zelfmeetapparatuur voor bloedstollingstijden'),
	new VektisCode('7651', 'Leveranciers hulpmiddelen, injectiespuiten'),
	new VektisCode('7656', 'Leveranciers hulpmiddelen, insuline-infuuspompen'),
	new VektisCode('7657', 'Leveranciers hulpmiddelen, overige hulpmiddelen bij diabetes'),
	new VektisCode('7661', 'Leveranciers hulpmiddelen, zuurstofapparaten en -concentrators'),
	new VektisCode(
		'7662',
		'Leveranciers hulpmiddelen, apparatuur voor verzekerden met ademhalingsstoornissen (CPAP)'
	),
	new VektisCode('7663', 'Leveranciers hulpmiddelen, apparatuur voor positieve uitademingsdruk'),
	new VektisCode('7666', 'Leveranciers hulpmiddelen, longvibrators'),
	new VektisCode('7671', 'Leveranciers hulpmiddelen, vernevelaars'),
	new VektisCode('7676', 'Leveranciers hulpmiddelen, beeldschermloep'),
	new VektisCode('7677', 'Leveranciers hulpmiddelen, tactiel leesapparatuur'),
	new VektisCode('7681', 'Leveranciers hulpmiddelen, elektrastimulator'),
	new VektisCode('7682', 'Leveranciers hulpmiddelen, botgroei-stimulators'),
	new VektisCode('7685', 'Leveranciers hulpmiddelen, hulpmiddelen voor het toedienen van voeding'),
	new VektisCode('7686', 'Leveranciers hulpmiddelen, dieetpreparaten'),
	new VektisCode('7687', 'Leveranciers hulpmiddelen, voeding'),
	new VektisCode('7688', 'Leveranciers hulpmiddelen, eetapparaten'),
	new VektisCode(
		'7689',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communicatie voor lichamelijk gehandicapten'
	),
	new VektisCode('7691', 'Leveranciers hulpmiddelen, inrichtingselementen van woningen'),
	new VektisCode(
		'7692',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communiatie persoonlijke alarmering'
	),
	new VektisCode(
		'7693',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communiatie-, wek- en waarschuwing'
	),
	new VektisCode(
		'7694',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communiatie bij revalidatie'
	),
	new VektisCode(
		'7695',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communicatie, informatie en signalering'
	),
	new VektisCode('7696', 'Leveranciers hulpmiddelen, fax-apparatuur voor auditief gehandicapten'),
	new VektisCode(
		'7697',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communicatie grootlettersystemen'
	),
	new VektisCode(
		'7698',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communicatie-, opname- en voorleesapparatuur'
	),
	new VektisCode(
		'7699',
		'Leveranciers hulpmiddelen, hulpmiddelen voor communicatie-, telefoons en telefoneerhulpmiddelen'
	),
	new VektisCode('7800', 'Sociaal pedagogische diensten'),
	new VektisCode('7900', "RIAGG's"),
	new VektisCode('8000', 'Niet erkende verpleeginrichtingen'),
	new VektisCode('8100', 'Niet erkende zwakzinnigeninrichtingen'),
	new VektisCode('8200', 'Bejaardenoorden'),
	new VektisCode('8300', 'Overige niet erkende instellingen'),
	new VektisCode('8400', 'Overige artsen, niet nader gespecificeerd'),
	new VektisCode('8401', 'Arts, chiropractie'),
	new VektisCode('8402', 'Arts, musculoskeletale geneeskunde'),
	new VektisCode('8403', 'Arts/tandarts Acupunctuur'),
	new VektisCode('8404', 'Arts, irisscopie'),
	new VektisCode('8405', 'Arts, homeopathie'),
	new VektisCode('8406', 'Arts, natuurgeneeskunde'),
	new VektisCode('8407', 'Arts, antroposofische geneeskunde'),
	new VektisCode('8408', 'Overige artsen, moermantherapie'),
	new VektisCode('8409', 'Arts, enzymtherapie'),
	new VektisCode('8410', 'Arts, manuele geneeskunde'),
	new VektisCode('8411', 'Arts, haptotherapie'),
	new VektisCode('8412', 'Arts, osteopathie'),
	new VektisCode('8413', 'Overige artsen, flebologie/proctologie'),
	new VektisCode('8414', 'Overige artsen, orthomoleculaire geneeskunde'),
	new VektisCode('8415', 'Overige artsen, neurale therapie'),
	new VektisCode('8416', 'Overige artsen, sportgeneeskunde'),
	new VektisCode('8417', 'Arts Spoedeisende Hulp (SEH)'),
	new VektisCode('8418', 'Overige artsen, specialist ouderengeneeskunde'),
	new VektisCode('8419', 'Overige artsen, schoolartsen'),
	new VektisCode('8420', 'Overige artsen, consultatiebureau-artsen'),
	new VektisCode('8421', 'Overige artsen, SCEN-arts'),
	new VektisCode('8422', 'Overige artsen, orthopedische geneeskunde'),
	new VektisCode('8423', 'Arts Tuberculosebestrijding'),
	new VektisCode('8424', 'Overige artsen, verslavingsartsen'),
	new VektisCode('8425', 'Overige artsen, basisarts'),
	new VektisCode('8426', 'Overige artsen, arts voor verstandelijk gehandicapten'),
	new VektisCode('8427', 'Overige artsen, arts palliatieve geneeskunde'),
	new VektisCode('8428', 'Overige artsen, jeugdarts'),
	new VektisCode('8429', 'Overige artsen, Klinisch Fysicus audioloog'),
	new VektisCode('8430', 'Arts Infectieziektebestrijding'),
	new VektisCode('8431', 'Medisch seksuoloog'),
	new VektisCode('8432', 'Klinisch technoloog'),
	new VektisCode('8433', 'Cosmetisch arts'),
	new VektisCode('8434', 'Ziekenhuisarts'),
	new VektisCode('8435', 'Arts Maatschappij en Gezondheid'),
	new VektisCode('8436', 'Arts Donorgeneeskunde'),
	new VektisCode('8500', 'Taxivervoerders'),
	new VektisCode('8600', 'Instellingen voor maatschappelijke dienstverlening'),
	new VektisCode('8700', 'Mondhygienisten'),
	new VektisCode('8800', 'Ergotherapeuten'),
	new VektisCode('8801', 'Ergotherapie, direct toegankelijk / 1e lijn'),
	new VektisCode('8810', 'Ergotherapeuten, ergotherapie, direct toegankelijk'),
	new VektisCode('8900', 'Schoonheidsspecialisten, niet nader gespecificeerd'),
	new VektisCode('8901', 'Schoonheidsspecialisten, acne'),
	new VektisCode('8902', 'Schoonheidsspecialisten, camouflage'),
	new VektisCode('8903', 'Schoonheidsspecialisten, elektrisch epileren'),
	new VektisCode('8904', 'Schoonheidsspecialist'),
	new VektisCode('8905', 'Acne'),
	new VektisCode('8906', 'Camouflage'),
	new VektisCode('8907', 'Elektrisch ontharen'),
	new VektisCode('8908', 'Schoonheidsspecialist(e), acne en camouflage.'),
	new VektisCode('8909', 'Schoonheidsspecialist(e), acne en elektrisch epileren.'),
	new VektisCode('8910', 'Schoonheidsspecialist(e), camouflage en elektrisch epileren.'),
	new VektisCode('8911', 'Schoonheidsspecialist(e), acne, camouflage en elektrisch epileren.'),
	new VektisCode('8912', 'Schoonheidsspecialist(e), niet ANBOS geregistreerd'),
	new VektisCode('8913', 'Ontharingstechnieken'),
	new VektisCode('8914', 'Schoonheidsspecialist(e), ontharingstechnieken en acne.'),
	new VektisCode('8915', 'Schoonheidsspecialist(e), ontharingstechnieken en camouflage.'),
	new VektisCode('8916', 'Schoonheidsspecialist(e), ontharingstechnieken, acne en camouflage.'),
	new VektisCode('8919', 'Schoonheidsspecialist(e), elektrisch epileren en ontharingstechnieken.'),
	new VektisCode('8920', 'Schoonheidsspecialist(e), Acne, camouflage en ontharingstechnieken.'),
	new VektisCode(
		'8921',
		'Schoonheidsspecialist(e), acne, elektrisch epileren en ontharingstechnieken.'
	),
	new VektisCode(
		'8922',
		'Schoonheidsspecialist(e), camouflage, elektrisch epileren en ontharingstechnieken.'
	),
	new VektisCode(
		'8923',
		'Schoonheidsspecialist(e), acne, camouflage, elektrisch epileren en ontharingstechnieken.'
	),
	new VektisCode('8924', 'Algemene schoonheids-specialist ANBOS geregistreerd, Acne.'),
	new VektisCode('9000', 'Overige therapeuten en Complementair en Aanvullende zorg'),
	new VektisCode('9001', 'Chiropractie'),
	new VektisCode('9002', 'Orthomanuele geneeskunde'),
	new VektisCode('9003', 'Acupunctuur'),
	new VektisCode('9004', 'Irisscopie'),
	new VektisCode('9005', 'Homeopathie'),
	new VektisCode('9006', 'Natuurgeneeskunde'),
	new VektisCode('9007', 'Antroposofische geneeskunde'),
	new VektisCode('9008', 'Moerman therapie'),
	new VektisCode('9009', 'Enzymtherapie'),
	new VektisCode('9010', 'Manuele geneeskunde'),
	new VektisCode('9011', 'Haptotherapie'),
	new VektisCode('9012', 'Osteopathie'),
	new VektisCode('9013', 'Huidtherapie'),
	new VektisCode('9014', 'Kunstzinnige therapie'),
	new VektisCode('9015', 'Podologie'),
	new VektisCode('9016', 'Orthomoleculaire geneeskunde'),
	new VektisCode('9017', 'Shiatsu therapie'),
	new VektisCode('9018', 'Echoscopie'),
	new VektisCode('9020', 'Seksuologen, Lid NVVS'),
	new VektisCode('9021', 'Overigen'),
	new VektisCode('9022', 'Cranio sacraal therapie'),
	new VektisCode('9023', 'Adem- en ontspanningstherapie methode van Dixhoorn'),
	new VektisCode('9024', 'Kindertherapie'),
	new VektisCode('9025', 'Vaktherapie'),
	new VektisCode('9026', 'Echoscopie NT'),
	new VektisCode('9027', 'Echoscopie SEO'),
	new VektisCode('9028', 'Echoscopie uitwendig'),
	new VektisCode('9029', 'Gewichtsconsulent'),
	new VektisCode('9030', 'Lactatiedeskundige'),
	new VektisCode('9031', 'Huidtherapie, direct toegankelijk'),
	new VektisCode('9032', 'Reflexzonetherapeut'),
	new VektisCode('9033', 'Doula'),
	new VektisCode('9034', 'Yogadocenten'),
	new VektisCode('9035', 'Sportmasseur'),
	new VektisCode('9036', 'Preventieve voetzorg'),
	new VektisCode('9037', 'Psychosociaal zorgverlener'),
	new VektisCode('9038', 'Leefstijlcoach'),
	new VektisCode('9039', 'Positieve gezondheid zorgverlener'),
	new VektisCode('9040', 'Eerste trimester SEO'),
	new VektisCode('9041', 'Tweede trimester SEO'),
	new VektisCode('9042', 'Biometrie echo'),
	new VektisCode('9043', 'Termijn echo'),
	new VektisCode('9044', 'Gynaecologische echo'),
	new VektisCode('9045', 'Counseling prenatale screening'),
	new VektisCode('9100', 'Verpleegkundigen, niet nader gespecificeerd'),
	new VektisCode('9101', 'Gespecialiseerd verpleegkundige, diabetes'),
	new VektisCode('9102', 'Gespecialiseerd verpleegkundige, incontinentie'),
	new VektisCode('9103', 'Gespecialiseerd verpleegkundige, wijk'),
	new VektisCode('9104', 'Gespecialiseerd verpleegkundige, wond'),
	new VektisCode('9105', 'Gespecialiseerd verpleegkundige, stoma'),
	new VektisCode('9106', 'Gespecialiseerd verpleegkundige, long'),
	new VektisCode('9107', 'Gespecialiseerd verpleegkundige, oncologie'),
	new VektisCode('9108', 'Gespecialiseerd verpleegkundige, transfer'),
	new VektisCode('9109', 'Verpleegkundigen niveau 4'),
	new VektisCode('9110', 'Verpleegkundigen niveau 5 of hoger'),
	new VektisCode('9111', 'Verzorgenden'),
	new VektisCode('9112', 'Verpleegkundigen niveau 4 PGB'),
	new VektisCode('9113', 'Verpleegkundigen niveau 5 PGB'),
	new VektisCode('9114', 'Verpleegkundigen niveau 4 en Verpleegkundigen niveau 4 PGB'),
	new VektisCode('9115', 'Verpleegkundigen niveau 5 en Verpleegkundigen niveau 5 PGB'),
	new VektisCode('9116', 'Sociaal Psychiatrisch Verpleegkundige (SPV)'),
	new VektisCode('9130', 'Verpleegkundig specialist, preventieve zorg bij somatische aandoeningen'),
	new VektisCode('9131', 'Verpleegkundig specialist, acute zorg bij somatische aandoeningen'),
	new VektisCode('9132', 'Verpleegkundig specialist, intensieve zorg bij somatische aandoeningen'),
	new VektisCode('9133', 'Verpleegkundig specialist, chronische zorg bij somatische aandoeningen'),
	new VektisCode('9134', 'Verpleegkundig specialist, geestelijke gezondheidszorg'),
	new VektisCode('9135', 'RIBIZ Verpleegkundig specialist, algemene Gezondheidszorg'),
	new VektisCode(
		'9140',
		'Verpleegkundig specialist, preventieve zorg bij somatische aandoeningen (9100 + 9130)'
	),
	new VektisCode(
		'9141',
		'Verpleegkundig specialist, acute zorg bij somatische aandoeningen (9100 + 9131)'
	),
	new VektisCode(
		'9142',
		'Verpleegkundig specialist, intensieve zorg bij somatische aandoeningen (9100 + 9132)'
	),
	new VektisCode(
		'9143',
		'Verpleegkundig specialist, chronische zorg bij somatische aandoeningen (9100 + 9133)'
	),
	new VektisCode('9144', 'Verpleegkundig specialist, geestelijke gezondheidszorg (9100 + 9134)'),
	new VektisCode('9150', 'Gespecialiseerd verpleegkundige, diabetes (9100 + 9101)'),
	new VektisCode('9151', 'Gespecialiseerd verpleegkundige, incontinentie (9100 + 9102)'),
	new VektisCode('9152', 'Gespecialiseerd verpleegkundige, wijk (9100 + 9103)'),
	new VektisCode('9153', 'Gespecialiseerd verpleegkundige, wond (9100 + 9104)'),
	new VektisCode('9154', 'Gespecialiseerd verpleegkundige, stoma (9100 + 9105)'),
	new VektisCode('9155', 'Gespecialiseerd verpleegkundige, long (9100 + 9106)'),
	new VektisCode('9156', 'Gespecialiseerd verpleegkundige, oncologie (9100 + 9107)'),
	new VektisCode('9157', 'Gespecialiseerd verpleegkundige, transfer (9100 + 9108)'),
	new VektisCode('9180', 'Verzorgende (ZZP)'),
	new VektisCode('9181', 'Verpleegkundige (ZZP)'),
	new VektisCode('9190', 'Administratieve eenheid (AE)'),
	new VektisCode('9200', 'Ziekenhuisvervangende thuiszorg (financiering 2e compartiment)'),
	new VektisCode('9300', 'Tandtechnici/tandprothetici, niet nader gespecificeerd'),
	new VektisCode('9301', 'Tandprotheticus'),
	new VektisCode('9302', 'Tandtechnicus'),
	new VektisCode('9400', 'Psychologische zorgverleners, niet nader gespecificeerd'),
	new VektisCode(
		'9401',
		'Psychologische zorgverleners, GZ-psychologie met eerstelijnskwalificatie'
	),
	new VektisCode('9402', 'Psychologische zorgverleners, psychotherapie'),
	new VektisCode('9403', 'Psychologische zorgverleners, sexuologie'),
	new VektisCode('9404', 'Psychologische zorgverleners, k&j-psychologie'),
	new VektisCode('9405', 'Psychologische zorgverleners, klinische psychologie'),
	new VektisCode('9406', 'Psychologische zorgverleners, GZ-psychologie'),
	new VektisCode('9407', 'Psychologische zorgverleners, GZ-psychologie, psychotherapie'),
	new VektisCode(
		'9408',
		'Psychologische zorgveleners, GZ-psychologie met eerstelijnskwalificatie, psychotherapie'
	),
	new VektisCode(
		'9409',
		'Psychologische zorgverleners, GZ-psychologie met eerstelijnskwalificatie, kinder- en jeugdpsychologie en/of NVO Orthopedagogie-Generalist'
	),
	new VektisCode(
		'9410',
		'Psychologische zorgverleners, psychotherapie, kinder- en jeugdpsychologie en/of NVO Orthopedagogie-Generalist'
	),
	new VektisCode(
		'9411',
		'Psychologische zorgverleners, GZ-psychologie, psychotherapie, kinder- en jeugdpsychologie en/of NVO Orthopedagogie-Generalist'
	),
	new VektisCode(
		'9412',
		'Psycho. zorgverl., GZ-psychologie met eerstelijnskwal., psychotherapie, kinder- en jeugdpsychologie en/of NVO  Orthopedagogie-Generalist'
	),
	new VektisCode(
		'9413',
		'Psychologische zorgverleners, klinische psychologie, kinder- en jeugdpsychologie en/of NVO Orthopedagogie-Generalist'
	),
	new VektisCode(
		'9414',
		'Psychologische zorgverleners, klinische psychologie met eerstelijnskwalificatie'
	),
	new VektisCode(
		'9415',
		'Psycho. zorgverl., klinisch psychologie met eerstelijnskwalificatie, kinder- en jeugdpsychologie en/of NVO Orthopedagogie-Generalist'
	),
	new VektisCode('9416', 'Psychologische zorgverleners, psycholoog NIP/ master-psycholoog SJK'),
	new VektisCode('9417', 'Orthopedagoog - generalist'),
	new VektisCode('9418', 'Psychologische zorgverleners, klinische neuropsychologie'),
	new VektisCode('9419', 'Psychologische zorgverleners, orthopedagogen (overig)'),
	new VektisCode('9420', 'Psychologische zorgverleners, orthopedagogen (basis)'),
	new VektisCode('9421', 'Kwaliteitsgeregistreerd ECP-therapeut'),
	new VektisCode('9422', 'ECP-therapeut'),
	new VektisCode('9423', 'Psychologische zorgverleners, kinder en jeugdpsycholoog nip'),
	new VektisCode('9424', 'Psychologische zorgverleners, klinische psychologie en psychotherapie'),
	new VektisCode(
		'9425',
		'Psychologische zorgverleners, klinische psychologie, 1e lijn en psychotherapie'
	),
	new VektisCode(
		'9426',
		'Psychologische zorgverleners, klinische psychologie, 1e lijn, psychotherapie, K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9427',
		'Psychologische zorgverleners, klinische psychologie, K&J psychologie en psychotherapie'
	),
	new VektisCode('9430', 'Psychologische zorgverleners, klinische neuropsychologie en 1e lijn'),
	new VektisCode(
		'9431',
		'Psychologische zorgverleners, klinische neuropsychologie en K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9432',
		'Psychologische zorgverleners, klinische neuropsychologie en klinische psychologie'
	),
	new VektisCode(
		'9433',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn en K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9434',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn en klinische psychologie'
	),
	new VektisCode(
		'9435',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn, klinische psychologie en K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9436',
		'Psychologische zorgverleners, klinische neuropsychologie en psychotherapie'
	),
	new VektisCode(
		'9437',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn  en psychotherapie'
	),
	new VektisCode(
		'9438',
		'Psychologische zorgverleners, klinische neuropsychologie, psychotherapie en K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9439',
		'Psychologische zorgverleners, klinische neuropsychologie, klinische psychologie en psychotherapie'
	),
	new VektisCode(
		'9440',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn, psychotherapie en K&J psychologie en/of orthopedagoog'
	),
	new VektisCode(
		'9441',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn, klinische psychologie en psychotherapie'
	),
	new VektisCode(
		'9442',
		'Psychologische zorgverleners, klinische neuropsychologie, 1e lijn, klinische psychologie, psychotherapie, K&J psychologie en/of orthopedag.'
	),
	new VektisCode(
		'9443',
		'Psychologische zorgverleners, klinische neuropsychologie, klinische psychologie, K&J psychologie en/of orthopedagoog.'
	),
	new VektisCode(
		'9444',
		'Psychologische zorgverleners, klinische neuropsychologie, klinische psychologie, psychotherapie, K&J psychologie en/of orthopedagoog.'
	),
	new VektisCode(
		'9445',
		'Psychologische zorgverleners, klinisch psychologie, gz-psychologie, psychotherapie'
	),
	new VektisCode(
		'9446',
		'Psychologische zorgverleners, klinisch psychologie, gz-psychologie, 1e lijn, psychotherapie'
	),
	new VektisCode(
		'9447',
		'Psychologische zorgverleners, klinisch psychologie, gz-psychologie, 1e lijn, psychotherapie, K&J psycholoog'
	),
	new VektisCode(
		'9448',
		'Psychologische zorgverleners, klinisch psychologie, gz-psychologie, psychotherapie, K&J psycholoog'
	),
	new VektisCode(
		'9449',
		'Psychologische zorgverleners, gz-psychologie 1e lijn, K&J psycho e/o orthopedagoog, psychotherapeut'
	),
	new VektisCode('9450', 'Psychologische zorgverleners, psycholoog NIP, gz psychologie'),
	new VektisCode('9451', 'Psychologische zorgverleners, psycholoog NIP, psychotherapeut'),
	new VektisCode(
		'9452',
		'Psychologische zorgverleners, kinder- en jeugdpsycholoog NIP, gz psychologie'
	),
	new VektisCode(
		'9453',
		'Psychologische zorgverleners, kinder- en jeugdpsycholoog NIP, psychotherapie'
	),
	new VektisCode('9454', 'Psychologische zorgverleners, psycholoog NIP, gz psychologie 1e lijn'),
	new VektisCode(
		'9455',
		'Psychologische zorgverleners, GZ-psycholoog, orthopedagoog (generalist, specialist)'
	),
	new VektisCode(
		'9456',
		'Psychologische zorgverleners, K&J-psycholoog, GZ-psycholoog, orthopedagoog (generalist, specialist)'
	),
	new VektisCode(
		'9457',
		'Psychologische zorgverleners, kinder- en jeugdpsycholoog NIP, GZ-psychologie, 1e lijn'
	),
	new VektisCode(
		'9458',
		'Psychologische zorgverleners, psycholoog NIP, orthopedagoog (generalist, specialist)'
	),
	new VektisCode('9459', 'Psychologische zorgverleners, psycholoog NIP, therapeut NVPA'),
	new VektisCode(
		'9460',
		'Psychologische zorgverleners, GZ-psycholoog, kinder- en jeugdpsycholoog NIP, orthopedagoog (generalist, specialist)'
	),
	new VektisCode(
		'9461',
		'Psychologische zorgverleners, klinisch psycholoog, kinder- en jeugdpsycholoog NIP'
	),
	new VektisCode('9462', 'Psychologische zorgverleners, psycholoog Arbeid en Gezondheid NIP'),
	new VektisCode('9463', 'Psychologische zorgverleners, master pedagoog'),
	new VektisCode('9464', 'Psychologische zorgverleners, jeugd- en gezinsprofessional'),
	new VektisCode('9465', 'Psychologische zorgverleners, kinder- en jeugdpsycholoog'),
	new VektisCode('9466', 'Psychologische zorgverleners, postmaster orthopedagoog'),
	new VektisCode('9467', 'Psychologische zorgverleners, GZ-psychologie 1e lijn, master pedagoog'),
	new VektisCode('9468', 'Psychologische zorgverleners, GZ-psychologie 1e lijn, jeugdzorgwerker'),
	new VektisCode(
		'9469',
		'Psychologische zorgverleners, kinder- en jeugdpsycholoog, postmaster orthopedagoog'
	),
	new VektisCode(
		'9470',
		'Psychologische zorgverleners, GZ-psycholoog 1e lijn, kinder- en jeugdpsycholoog, postmaster orthopedagoog'
	),
	new VektisCode(
		'9471',
		'Klinische psychologie,GZ-Psycholoog, Psycholoog NIP/ MasterPsycholoog SKJ'
	),
	new VektisCode('9472', 'Klinische psychologie,GZ-Psycholoog, Kinder en Jeugdpsycholoog NIP'),
	new VektisCode('9473', 'GZ-Psycholoog, Klinische neuropsychologie'),
	new VektisCode('9500', 'Orthopedagogen'),
	new VektisCode('9600', 'Pedicuren'),
	new VektisCode('9601', 'Pedicure'),
	new VektisCode('9602', 'Pedicure, specialisatie reumatische voet'),
	new VektisCode('9603', 'Pedicure, specialisatie diabetische voet'),
	new VektisCode('9604', 'Pedicure, specialisatie reumatische voet + diabetische voet'),
	new VektisCode('9605', 'Pedicure, specialisatie medische pedicure'),
	new VektisCode('9606', 'Pedicure,  pedicure in de zorg'),
	new VektisCode('9607', 'Pedicure,  registerpedicure'),
	new VektisCode('9608', 'Pedicure,  paramedisch chiropodist'),
	new VektisCode('9609', 'Pedicure, specialisatie Risicovoet'),
	new VektisCode('9800', 'Declaranten'),
	new VektisCode('9801', 'Servicebureau'),
	new VektisCode('9802', 'Aanbieder Maatschappelijke ondersteuning / JeugdzorgWMO'),
	new VektisCode('9803', 'Zorgverzekeraar'),
	new VektisCode('9804', 'Aanbieder PGB WLZ'),
	new VektisCode('9805', ' Reisverzekeraar'),
	new VektisCode('9900', 'Overigen'),
	new VektisCode('9901', 'Verpleeghuisartsen'),
	new VektisCode('9902', 'Bedrijfsarts'),
	new VektisCode('9903', 'Schoolarts'),
	new VektisCode('9904', 'Sportarts')
];
